### ISSUE TITLE
Permission denied during installation

### ISSUE THREAD

**Issue by antkachenko** [homespun/homebridge-accessory-apcupsd#1]
Hello,

During the installation got the following error message. What am I doing wrong?

root@RPi-iLona:~/.homebridge# npm -g install homebridge-accessory-apcupsd
npm ERR! code 1
npm ERR! Command failed: git clone --mirror -q https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-a6897fd2/.git
npm ERR! /root/.npm/_cacache/tmp/git-clone-a6897fd2/.git: Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-19T18_14_34_003Z-debug.log

**Comment by antkachenko** [comment]
Does this project alive?

**Comment by mrose17** [comment]
yes, the project lives, though i'm often too busy to check in more than once a month.

did you see this from the README?

    NB: If you install homebridge like this:
        sudo npm install -g --unsafe-perm homebridge
    Then all subsequent installations must be like this:
        sudo npm install -g --unsafe-perm homebridge-accessory-apcupsd

did you try it and did it work?

**Comment by antkachenko** [comment]
I've installed homebridge without --unsafe-perm option. Should I use it to make homebridge-accessory-apcupsd working?

Tryed to reinstall homebridge with --unsafe-perm, tryed to install homebridge-accessory-apcupsd with same result. Log here: https://drive.google.com/open?id=1-LtEV2uFYOYZJsbRbg8ZVD38kUAWvSW5

**Comment by mrose17** [comment]
i don't have an answer. sadly, i've never understood why "this just works" for some installations and doesn't work for others. i've never been able to find the pattern. sorry!

**Comment by r4zr1** [comment]
> I've installed homebridge without --unsafe-perm option. Should I use it to make homebridge-accessory-apcupsd working?
> 
> Tryed to reinstall homebridge with --unsafe-perm, tryed to install homebridge-accessory-apcupsd with same result. Log here: https://drive.google.com/open?id=1-LtEV2uFYOYZJsbRbg8ZVD38kUAWvSW5

Just reinstall node.js with node version manager with this instruction
https://docs.npmjs.com/downloading-and-installing-node-js-and-npm
and do the `sudo chown -R <uid>:<guid> "/home/<user>/.npm"` 

Personally I'm installed this one https://github.com/nodesource/distributions

**Node.js v12.x:**
```
-Using Ubuntu
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

-Using Debian, as root
curl -sL https://deb.nodesource.com/setup_12.x | bash -
apt-get install -y nodejs
```
